server:
    port: 8080
spring:
  application:
    name: tc-api
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
            auto-commit: false
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show-sql: true
# Specifying the following key entries in mixed cases due to YAML/Spring-boot limitation...    
authHeaderValue: x-api-key
authHeaderValue: GtJk9fqeCV5W99H7g65kH6S6pWLE0JBw51lYjYH3
awsApiGateWayUri: https://aztj5hht4a.execute-api.us-east-1.amazonaws.com/dev
multiModalQueryByImageUri: https://aztj5hht4a.execute-api.us-east-1.amazonaws.com/dev/v3/multimodal
multiModalQueryByImageUriDirect: http://54.87.37.76:5001/v3/multimodal